/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedPlannedVsActualRouteImport } from './routes/_authenticated/planned-vs-actual'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLogRunRouteImport } from './routes/_authenticated/log-run'
import { Route as AuthenticatedGeneratorRouteImport } from './routes/_authenticated/generator'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedWorkoutIdRouteImport } from './routes/_authenticated/workout.$id'
import { Route as ApiPublicStravaWebhookRouteImport } from './routes/api/public/strava/webhook'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannedVsActualRoute =
  AuthenticatedPlannedVsActualRouteImport.update({
    id: '/planned-vs-actual',
    path: '/planned-vs-actual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogRunRoute = AuthenticatedLogRunRouteImport.update({
  id: '/log-run',
  path: '/log-run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGeneratorRoute = AuthenticatedGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkoutIdRoute = AuthenticatedWorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicStravaWebhookRoute = ApiPublicStravaWebhookRouteImport.update({
  id: '/api/public/strava/webhook',
  path: '/api/public/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/log-run': typeof AuthenticatedLogRunRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planned-vs-actual': typeof AuthenticatedPlannedVsActualRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/workout/$id': typeof AuthenticatedWorkoutIdRoute
  '/api/public/strava/webhook': typeof ApiPublicStravaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/log-run': typeof AuthenticatedLogRunRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planned-vs-actual': typeof AuthenticatedPlannedVsActualRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/workout/$id': typeof AuthenticatedWorkoutIdRoute
  '/api/public/strava/webhook': typeof ApiPublicStravaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generator': typeof AuthenticatedGeneratorRoute
  '/_authenticated/log-run': typeof AuthenticatedLogRunRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planned-vs-actual': typeof AuthenticatedPlannedVsActualRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/workout/$id': typeof AuthenticatedWorkoutIdRoute
  '/api/public/strava/webhook': typeof ApiPublicStravaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/calendar'
    | '/dashboard'
    | '/generator'
    | '/log-run'
    | '/onboarding'
    | '/planned-vs-actual'
    | '/progress'
    | '/settings'
    | '/upload'
    | '/workout/$id'
    | '/api/public/strava/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activities'
    | '/calendar'
    | '/dashboard'
    | '/generator'
    | '/log-run'
    | '/onboarding'
    | '/planned-vs-actual'
    | '/progress'
    | '/settings'
    | '/upload'
    | '/workout/$id'
    | '/api/public/strava/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activities'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/generator'
    | '/_authenticated/log-run'
    | '/_authenticated/onboarding'
    | '/_authenticated/planned-vs-actual'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/_authenticated/workout/$id'
    | '/api/public/strava/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicStravaWebhookRoute: typeof ApiPublicStravaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planned-vs-actual': {
      id: '/_authenticated/planned-vs-actual'
      path: '/planned-vs-actual'
      fullPath: '/planned-vs-actual'
      preLoaderRoute: typeof AuthenticatedPlannedVsActualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log-run': {
      id: '/_authenticated/log-run'
      path: '/log-run'
      fullPath: '/log-run'
      preLoaderRoute: typeof AuthenticatedLogRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generator': {
      id: '/_authenticated/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AuthenticatedGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workout/$id': {
      id: '/_authenticated/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof AuthenticatedWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/strava/webhook': {
      id: '/api/public/strava/webhook'
      path: '/api/public/strava/webhook'
      fullPath: '/api/public/strava/webhook'
      preLoaderRoute: typeof ApiPublicStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGeneratorRoute: typeof AuthenticatedGeneratorRoute
  AuthenticatedLogRunRoute: typeof AuthenticatedLogRunRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlannedVsActualRoute: typeof AuthenticatedPlannedVsActualRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedWorkoutIdRoute: typeof AuthenticatedWorkoutIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGeneratorRoute: AuthenticatedGeneratorRoute,
  AuthenticatedLogRunRoute: AuthenticatedLogRunRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlannedVsActualRoute: AuthenticatedPlannedVsActualRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedWorkoutIdRoute: AuthenticatedWorkoutIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicStravaWebhookRoute: ApiPublicStravaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
